### ISSUE TITLE
Examples page shown everytime I open VSCode 

### ISSUE THREAD

**Issue by rido-min** [microsoft/devkit-sdk#1008]
Since I installed the Azure IoT Device Workbench, everytime I open VSCode, even for non-IoT related projects, the Examples page gets on my way and I need to close it.

Is it possible to disable it?

**Comment by ArthurMa1978** [comment]
Thanks @rido-min 
Because the IoT DevKit is connected :)
But anyway it's really noisy, will improve it in next version.

**Comment by ArthurMa1978** [comment]
We added a checkbox on the bottom of the example page which can disable auto popup.
![image](https://user-images.githubusercontent.com/20514459/60932872-7b8af380-a2f2-11e9-80e9-067b96a41121.png)

Thanks @rido-min !
