### ISSUE TITLE
MXCHIP AZ3166 serial port issue

### ISSUE THREAD

**Issue by br1pro** [microsoft/devkit-sdk#1009]
I'm following this tutorial https://microsoft.github.io/azure-iot-developer-kit/docs/get-started/ to connect my AZ3166 to Iot Hub. 
The tutorial explain how to run the "Get started" tutorial.
In the section "Build your first project" I'm blocked at point 5. If I click on the "select serial port" button in the right down corner, nothing happens.
I'm using the last firmware 1.6.2 and visual studio code on a win10 pc.

**Comment by br1pro** [comment]
![image](https://user-images.githubusercontent.com/23063162/60703178-6896ae80-9f01-11e9-943a-143fb30b2eb0.png)

**Comment by br1pro** [comment]
The serial port works well if I try to open it from Putty, so I think this is a VScode issue

**Comment by ArthurMa1978** [comment]
https://github.com/microsoft/vscode-iot-workbench/issues/661

fixed since the VS Code workbench v0.3.1
