### ISSUE TITLE
Support Plug & Play

### ISSUE THREAD

**Issue by ArthurMa1978** [microsoft/devkit-sdk#1015]
https://channel9.msdn.com/Shows/Internet-of-Things-Show/Introduction-to-IoT-Plug-and-Play

**Comment by dooriya** [comment]
We've already shipped the SDK with PnP feature from 1.9.9 version.
If you want to try the PnP feature with DevKit, please use [this borad URL](https://raw.githubusercontent.com/VSChina/azureiotdevkit_tools/pnp/package_mxchip_board_index.json) to download and install the package.
