### ISSUE TITLE
Platform IO support

### ISSUE THREAD

**Issue by fmuntean** [microsoft/devkit-sdk#1021]
Currently the VS Code Platform IO is pointing to a very old version of this SDK.
Can somebody update the Platform IO package to the latest SDK so we do not need to rely on Arduino App being installed locally.
While Arduino IDE is more for a hobby/small project the  Platform IO is a more professional platform and allows for targeting the app towards multiple boards and/or configurations.

Would be great if Microsoft adds official support for the Platform IO for this board.

**Comment by xinyiz1226** [comment]
I see you already created an issue in platformio side here: https://github.com/platformio/platform-ststm32/issues/273. Let's track it from there.
