### ISSUE TITLE
Documentation does not match the API for WiFiServer accept

### ISSUE THREAD

**Issue by fmuntean** [microsoft/devkit-sdk#1024]
The documentation https://microsoft.github.io/azure-iot-developer-kit/docs/apis/wifi-server/#accept
Specifies that the accept method should exist however in SDK 1.6.2 is not inside the https://github.com/microsoft/devkit-sdk/blob/master/AZ3166/src/libraries/WiFi/src/AZ3166WiFiServer.h

Please update the documentation.

**Comment by dooriya** [comment]
Thank you for reporting this, we will update soon.

**Comment by dooriya** [comment]
API document has been updated https://microsoft.github.io/azure-iot-developer-kit/docs/apis/wifi-server/
