### ISSUE TITLE
[Feature Request] Ability to join enterprise WiFi

### ISSUE THREAD

**Issue by sfletc** [microsoft/devkit-sdk#1029]
Unless I'm missing something, this library doesn't allow for joining an enterprise WiFi network such as eduroam, where a username and password are required.  

Would be nice feature, as the device could then be used at universities as a great IOT learning platform.

**Comment by liydu** [comment]
@sfletc , DevKit supports connecting WiFi via username / password: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-iot-devkit-az3166-get-started. Are you talking about the captive portal like those in Starbucks which you connect to a hotspot and it pops up a page for username and password?

**Comment by sfletc** [comment]
WPA2 Enterprise Wifi requires an SSID, username and password.  It's not the same as in the getting started guide (which is fine for a home WPA2 router) or a captive portal like starbucks.  

Authentication is via EAP-TTLS or PEAP on eduroam, for example.  Other devices like the ESP32 are capable (e.g. https://github.com/espressif/esp-idf/tree/master/examples/wifi/wpa2_enterprise); just trying to work out whether this one is, so it can be used as a learning tool.

**Comment by liydu** [comment]
DevKit uses cypress bcm43362, unfortunately, it does not support WPA2 Enterprise.

**Comment by dooriya** [comment]
Close this issue since it is out-of-scope
