### ISSUE TITLE
Broken link in arduino board manager: java.net.UnknownHostException: azureboard.azureedge.net

### ISSUE THREAD

**Issue by mnogas** [microsoft/devkit-sdk#1077]
The tools required to install the mx board are currently unavailable: java.lang.Exception: Error downloading https://azureboard.azureedge.net/toolchain/gcc-arm-none-eabi-5_4-2016q3-20160926-win32.zip This has been raised on gitter since Mid-december. Please fix!

**Comment by asergaz** [comment]
this is now fixed. #please-close
