### ISSUE TITLE
Make proper email promotions for DevKit 

### ISSUE THREAD

**Issue by chyuanmsft** [Microsoft/devkit-sdk#615]
[For Tracking Purpose] Email promotion is the third largest referrer to DevKit site. Please refer S124 writeup for more details.

**Comment by ArthurMa1978** [comment]
look like gitter is a good channel

**Comment by liydu** [comment]
We will set up another beta group for early adopters. Rest we will maintain the Gitter which proved to be an effective channel for community

**Comment by ArthurMa1978** [comment]
will broadcasting the release information in the gitter channel
