### ISSUE TITLE
Support watchdog timer

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#673]

**Comment by ArthurMa1978** [comment]
Due the limited resource in S132, postpone to next sprint

**Comment by ihere1** [comment]
https://github.com/Microsoft/devkit-sdk/pull/810

**Comment by v-fional** [comment]
Closed as fixed, please refer to the following test result:

If the time reach the configured time, the watchdog trigger a system reset, and the value of resetTriggered() is 1;
otherwise, the watchdog is not trigger a system reset, and the value of resetTriggered() is 0

**Comment by v-fional** [comment]
please refer to doc https://microsoft.github.io/azure-iot-developer-kit/docs/apis/watchdog-timer/
