### ISSUE TITLE
Enable mbed_memory_status function

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#675]

**Comment by dooriya** [comment]
Enable mbed-os 5 run-time statistics for IoT DevKit
For more details, please refer to https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/runtime_stats/

Will release this change in next release.

**Comment by ArthurMa1978** [comment]
Should document it in our site

**Comment by v-fional** [comment]
checked on the latest code, the function works well.
