### ISSUE TITLE
Provide more information during task device-upload verification

### ISSUE THREAD

**Issue by likidu** [Microsoft/devkit-sdk#724]
Now it stays at "... Verification..." for a couple of minutes or so. Will be good to expose more context information for that step.

**Comment by Sneezry** [comment]
The console log is provided by Arduino IDE, and we don't handle when and what should be printed in the script. I'm afraid it's hard to inject some output while Arduino IDE is running.

**Comment by Sneezry** [comment]
Moved to https://github.com/Microsoft/vscode-iot-dev-env/issues/45
