### ISSUE TITLE
Throw error when executing ‘az –version’ command

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#740]
Task   install Azure CLI failed: Error: Unexpected error when executing   "C:\\Program Files (x86)\\Microsoft   SDKs\\Azure\\CLI2\\wbin\\az.cmd" --version : Command failed:   "C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin\\az.cmd"   --version     . Error: Command failed: "C:\\Program Files (x86)\\Microsoft   SDKs\\Azure\\CLI2\\wbin\\az.cmd" --version              at ChildProcess.exithandler   (child_process.js:275:12)         at emitTwo   (events.js:126:13)         at ChildProcess.emit   (events.js:214:7)         at maybeClose   (internal/child_process.js:925:16)         at   Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Package version 1.3.1
Platform: win32
Time: 1/28/2018   3:17:59 PM

**Comment by ihere1** [comment]
No more change in installation script later.
