### ISSUE TITLE
Windows user that could not get Visual Studio code to recognize the MXChip/port

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#744]
3I had a Windows user that could not get Visual Studio code to recognize the MXChip/port.  We tried un-installing, re-installing, re-selecting the board manager both in VS Code as well as in the Arduino IDE, no luck.   In VS Code, when trying to select the MXChip board, the Upload Method selection wasn’t visible:

![image](https://user-images.githubusercontent.com/20514459/35715973-bbac7ae8-0810-11e8-9d26-70a2e24eca9b.png)

**Comment by lirenhe** [comment]
I would suggest updating the document on how to workaround this issue.
Just one line change in the config file.
I worked with people for Arduino extension but still unable to figure out the root cause.

**Comment by BretStateham** [comment]
What is the "one line" to change in the config file?

**Comment by lirenhe** [comment]
@BretStateham , open arduino.json under .vscode folder for the mini solution, modify the configuration part to the following line:
    "configuration": "upload_method=OpenOCDMethod"

**Comment by ArthurMa1978** [comment]
Will provide a FAQ

**Comment by lirenhe** [comment]
FAQ added in https://microsoft.github.io/azure-iot-developer-kit/docs/faq/
