### ISSUE TITLE
The node.js not in the system PATH env

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#745]
I had another attendee where they installed node.js via the devkit, however it would never resolve inside the VS Code integrated terminal (even after closing and restarting VS code).  I had her manually install node from the web site, making sure to include Node in the path, and that fixed it.

**Comment by ArthurMa1978** [comment]
Try to repo this issue first

**Comment by v-fional** [comment]
We tried the following scenarios, but hard to repo this issue.

1. If uninstall nodejs, and make sure the variable is removed from the Path env, then run the installation script, the nodejs is installed with variable added to the Path env

2. Just remove the variable from the Path env, then run the installation script, the installation is failed with "Error occurred when running yarn install" error.

**Comment by ArthurMa1978** [comment]
Rare case and hard to repo, and since we are working on the new VS Code extension to replace the installation script, so close this issue.
