### ISSUE TITLE
fatal error: Riot.h: No such file or directory  #include "Riot.h"

### ISSUE THREAD

**Issue by adumont** [Microsoft/devkit-sdk#757]
Verifying...
In file included from /home/adumont/.arduino15/packages/AZ3166/hardware/stm32f4/1.3.2/libraries/AzureIoT/src/DevkitDPSClient.cpp:6:0:
/home/adumont/.arduino15/packages/AZ3166/hardware/stm32f4/1.3.2/cores/arduino/az_iot/provisioning_client/deps/RIoT/Reference/RIoT/Core/RiotCore.h:14:18: fatal error: Riot.h: No such file or directory
 #include "Riot.h"
                  ^
compilation terminated.
exit status 1
[Error] Exit with code=1

**Comment by adumont** [comment]
Fixed in https://github.com/Microsoft/devkit-sdk/pull/756

**Comment by ArthurMa1978** [comment]
Thanks  Alexandre, this will be in [1.3.3 release](https://github.com/Microsoft/devkit-sdk/issues/762).

**Comment by v-fional** [comment]
Tested on the latest code, it works well without any exception

**Comment by adumont** [comment]
Fixed in #798
