### ISSUE TITLE
Remote monitoring sample warning on task

### ISSUE THREAD

**Issue by liydu** [Microsoft/devkit-sdk#765]
WARNING: This command is deprecating and will be removed in future releases. Use 'az iot hub device-identity list (via IoT Extension)' instead.

**Comment by ihere1** [comment]
https://github.com/Azure/azure-iot-cli-extension Seems a cli-extension is needed for device-identity

**Comment by ihere1** [comment]
We are going to release vscode extension. See what **IoT Workbench** can do.

**Comment by ihere1** [comment]
No more change in installation script later.
