### ISSUE TITLE
Figure out DevKit + IoT Edge solutions

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#792]
1. Transparent gateway
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway

2. Connect MQTT module on IoT Edge

**Comment by v-fional** [comment]
Please refer to https://github.com/DevKitExamples/DevKitModbus#connect-to-iot-edge-device-gateway-as-modbus-tcp-device).
