### ISSUE TITLE
[GDPR] Do not send project name in plain text

### ISSUE THREAD

**Issue by chyuanmsft** [Microsoft/devkit-sdk#796]
The tasks now send project name in telemetry to help us understand usage of our mini solutions. After discussed offline, please hash the project name before sending telemetry.

**Comment by chyuanmsft** [comment]
Please use a new property "hash_project_name" to save hashed value so we don't need to worry about what the project_name column stores.

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/38966858-e81a6f40-43b6-11e8-9592-c6aa239e3ef9.png)

![image](https://user-images.githubusercontent.com/35018765/38966868-f2e6739c-43b6-11e8-8865-484fdc424315.png)

![image](https://user-images.githubusercontent.com/35018765/38966877-fc7424ea-43b6-11e8-89fb-ecbcb78034f3.png)

**Comment by czgtest** [comment]
Fix work now 
![image](https://user-images.githubusercontent.com/35018765/39035227-d11c77d4-44ab-11e8-9dbc-d65b74991719.png)
