### ISSUE TITLE
One-click installer fails to find VS code path

### ISSUE THREAD

**Issue by pemj** [Microsoft/devkit-sdk#826]
When running the [one-click installer](https://aka.ms/devkit/prod/installpackage/latest) on Windows 10, I encountered an issue installing the VS Code extension. The script detected that I already have VS Code installed, but when it attempts to run it in order to install the extension via 
`C:\Program Files (x86)\Microsoft VS Code\bin\code`
it was unable to locate the path.  I've got VS Code under 
`C:\Program Files\Microsoft VS Code\bin\code`

It looks like the script, at line 18 of
`/out/tasks/task-installation.js`
defines the path like so:
`_vsCodeExePath = _path2.default.join(process.env['ProgramFiles'], 'Microsoft VS Code', 'bin', 'code');`

I was able to proceed through the rest of the script by manually installing the extension to VS Code, but wanted to point this out, since I didn't see it listed in troubleshooting section.

**Comment by ihere1** [comment]
@pemj Did you use our latest install package? If vscode with version newer than 1.13.1 detected. We will install extension by "code --install-extension xxxx" instead of full vscode path
