### ISSUE TITLE
Remove sdk dependency from installation script

### ISSUE THREAD

**Issue by ihere1** [Microsoft/devkit-sdk#832]
Suppose we will not release installation script after 1.3.6. . Need to remove sdk from installation package and get latest sdk by Arduino in installation script.

**Comment by v-fional** [comment]
The code is update, it contains the following 2 items:

1. Remove sdk from the installation package
2. Install the latest sdk, not specific version

**Comment by v-fional** [comment]
Tested on version 1.3.7, it works well, so close it
