### ISSUE TITLE
[User Feedback] Improve error message for serial port access denied

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/devkit-sdk#834]
> Not report “config iot hub device connection string failed: opening com4: access denied”, use "Serial Port already occupied"

**Comment by v-fional** [comment]
The code is updated, please review the PR: [#34808](https://mseng.visualstudio.com/VSIoT/IoT%20Dev%20Kit/_git/IoTDevKitInstallation.Win/pullrequest/348082?_a=overview)

**Comment by v-fional** [comment]
Tested on version 1.3.7, the error message changes to "Config IoT Hub device connection string failed: Opening COM4: Serial Port already occupied", so close this issue
