### ISSUE TITLE
The rule of temperatureAlert is wrong

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#835]
Should be like this:

```DevKitMQTTClient_Event_AddProp(message, "temperatureAlert", temperatureAlert > 30 ? "true" : "false");```

**Comment by v-fional** [comment]
code is updated, please refer to PR #[837 ](https://github.com/Microsoft/devkit-sdk/pull/837)

**Comment by v-fional** [comment]
Checked on version 1.3.7, it is fixed so close it

**Comment by ihere1** [comment]
Following device message shows that the original code is correct. Please help revert the code.

6/11/2018 10:56:23 AM> Device: [AZ3166], Data:[{
    "deviceId": "AZ3166",
    "messageId": 20,
    "temperature": 31.299999,
    "humidity": 75.099998
}]Properties:
'temperatureAlert': 'true'

6/11/2018 10:56:34 AM> Device: [AZ3166], Data:[{
    "deviceId": "AZ3166",
    "messageId": 21,
    "temperature": 30.100000,
    "humidity": 65.400002
}]Properties:
'temperatureAlert': 'true'

6/11/2018 10:56:45 AM> Device: [AZ3166], Data:[{
    "deviceId": "AZ3166",
    "messageId": 22,
    "temperature": 29.400000,
    "humidity": 63.700001
}]Properties:
'temperatureAlert': 'false'

**Comment by ihere1** [comment]
https://github.com/Microsoft/devkit-sdk/pull/851
