### ISSUE TITLE
[NOTE] Deprecate existing installation package

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#850]
As we are moving to the new [IoT Workbench](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-iot-workbench), the DevKit will be full supported by this new VS Code extension, which will be more convenient for developing, less tooltrain acquisition paints and more straightforward on creating a IoT Solution.

We will deprecate current installation package, which includes:
 - Installation scripts
 - Task scripts for all examples
 - All binaries

We will keep delivering new SDK library for IoT DevKit, add new features and fix bugs.
This is not a 'deprecation' of the IoT DevKit, but a 'evolution' which will lead to a new IoT E2E dev experience.

> 'Deprecation' not mean 'Disappearance', all historic packages are still keeping for downloading.

**Comment by v-fional** [comment]
The script is updated, please help to review it, thanks a lot.

PR: https://github.com/Microsoft/devkit-sdk/pull/855

It contains:
1. Only upload AZ3166 folder to azure blob
2. Update package_azureboard_index.json file
