### ISSUE TITLE
useless comparisons

### ISSUE THREAD

**Issue by Adamantinu** [Microsoft/devkit-sdk#863]
In the GetStarted Example there are useless comparisons like
 if (humidity != humidity) 
{
json_object_set_null(root_object, "humidity");
}

Those could be confusing for starters with the DevKit.
Please remove them.

**Comment by ArthurMa1978** [comment]
not useless, send the humidity to IoT hub only it has changed

**Comment by Adamantinu** [comment]
float humidity = readHumidity(); //Here you read the value of the humidity sensor
...
if (humidity != humidity) //Here you compare the value of the humidity Sensor you read out, to its self
{} //Therfore this Code will never be executed since the same variable can't have two values at once

Please correct me if I'm wrong, since i am normally developing in C#

**Comment by ArthurMa1978** [comment]
My bad, didn't review the code carefully.
Stupid bug!!! will fix it soon.

**Comment by Adamantinu** [comment]
No Problem, I'm happy to help.
