### ISSUE TITLE
Fix memery leak in /AZ3166/src/libraries/WiFi/src/AZ3166WiFiUdp.cpp

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/devkit-sdk#957]
Multiple call of int WiFiUDP::beginPacket(IPAddress ip, unsigned short port) would cause SocketAddress initialized multiple times and this would cause memory leak.

**Comment by ArthurMa1978** [comment]
https://github.com/Microsoft/devkit-sdk/pull/970
https://github.com/Microsoft/devkit-sdk/pull/969
https://github.com/Microsoft/devkit-sdk/pull/968
