### ISSUE TITLE
HttpClient not working with HTTPS urls

### ISSUE THREAD

**Issue by DerekFoster1976** [microsoft/devkit-sdk#971]
Cannot get any HTTPS REest calls to work. Have tried multiple APIs with correct cert fingerprint. Even the official sample code for HttpClient using HTTPS [here](https://microsoft.github.io/azure-iot-developer-kit/docs/apis/http-client/) doesn't work either. Standard HTTP calls work fine. There is a lot of discussion around this for standard Arduino sketches with mixed results. A solution would be great as essentially can't call most APIs directly from the board as they all use HTTPS.

**Comment by ArthurMa1978** [comment]
@DerekFoster1976  thank you for feedback.
Yes, this HttpClient doesn't support HTTPS, add this to feature backlog

**Comment by JerryYangKai** [comment]
Hi @DerekFoster1976 , We have released DevKit SDK 1.6.5 and HttpClient supporting HTTPS now. Please try it.
